repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: remove-crlf
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: 0a943e8cbbdfd4a4b33f15e77c542715b4964f65
    hooks:
      - id: go-fmt
      - id: go-build
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.0.0-alpha.1
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@6.8.0
          - eslint-config-standard@14.1.0
          - eslint-plugin-import@2.20.1
          - eslint-plugin-node@11.0.0
          - eslint-plugin-promise@4.2.1
          - eslint-plugin-standard@4.0.1
          - eslint-plugin-vue@6.2.1
        types: [file]
        args: [--fix]
        files: \.(js|vue)$

exclude: vendor|go\.(sum|mod)
