name: go mod tidy
on:
  pull_request:
    paths:
      - 'go.mod'

# Based on: https://github.com/transcom/mymove/blob/master/.github/workflows/go-auto-approve.yml
jobs:
  tidy:
    name: run go mod tidy and update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Tidy
        run: go mod tidy
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      - name: set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      - name: commit and push changes
        run: |
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m 'Execute `go mod tidy`'
            git push
          fi
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
