name: docker-build

on:
  pull_request:
  push:
    branches: [master]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build .
